apiVersion: apps/v1
kind: Deployment
metadata:
  name: bonvoyage-mysql
  labels:
    app: mysql-deployment
    owner: daniilkoziura
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bonvoyage-mysql
  template:
    metadata:
      labels:
        app: bonvoyage-mysql
    spec:
      volumes:
        - name: mysql-persistent-storage
      containers:
        - name: container-mysql
          image: mysql:5.7
          env:
            - name: MYSQL_USER
              value: "sail"
            - name: MYSQL_PASSWORD
              value: "password"
            - name: MYSQL_DATABASE
              value: "bonvoyage"
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: ./mysql