apiVersion: v1
kind: Pod
metadata:
  name: bonvoyage-front
  labels:
    env  : prod
    app  : main
    tier : frontend
    owner: DaniilKoziura
spec:
  containers:
    - name: container-react
      image: daniilkoziura/bonvoyage-frontend-kubernetes:latest
      ports:
        - containerPort: 3000