apiVersion: v1
kind: Pod
metadata:
  name: bonvoyage-mysql
  labels:
    env  : prod
    app  : main
    tier : frontend
    owner: DaniilKoziura
spec:
  containers:
    - name: container-mysql
      image: mysql:5.7
      env:
        - name: "MYSQL_USER"
          value: "sail"
        - name: "MYSQL_PASSWORD"
          value: "password"
        - name: "MYSQL_DATABASE"
          value: "bonvoyage"
        - name: "MYSQL_ROOT_PASSWORD"
          value: "password"
      ports:
        - containerPort: 3306
          name: mysql
      volumeMounts:
        - name: mysql-persistent-storage
          mountPath: ./mysql
  volumes:
    - name: mysql-persistent-storage