apiVersion: apps/v1
kind: Deployment
metadata:
  name: bonvoyage-frontend
  labels:
    app: bonvoyage-frontend
    env: prod
    owner: daniilkoziura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bonvoyage-frontend
  template:
    metadata:
      labels:
        app: bonvoyage-frontend
    spec:
      containers:
      - name: bonvoyage-frontend
        image: daniilkoziura/bonvoyage-frontend-kubernetes:version11
        ports:
          - containerPort: 3000